export enum MedicalSpecialty {
  ACUPUNTURA = "Acupuntura",
  ALERGIA_IMUNOLOGIA = "Alergia e Imunologia",
  ANESTESIOLOGIA = "Anestesiologia",
  ANGIOLOGIA = "Angiologia",
  CARDIOLOGIA = "Cardiologia",
  CIRURGIA_CARDIOVASCULAR = "Cirurgia Cardiovascular",
  CIRURGIA_DA_MAO = "Cirurgia da Mão",
  CIRURGIA_CABECA_PESCOCO = "Cirurgia de Cabeça e Pescoço",
  CIRURGIA_APARELHO_DIGESTIVO = "Cirurgia do Aparelho Digestivo",
  CIRURGIA_GERAL = "Cirurgia Geral",
  CIRURGIA_ONCOLOGICA = "Cirurgia Oncológica",
  CIRURGIA_PEDIATRICA = "Cirurgia Pediátrica",
  CIRURGIA_PLASTICA = "Cirurgia Plástica",
  CIRURGIA_TORACICA = "Cirurgia Torácica",
  CIRURGIA_VASCULAR = "Cirurgia Vascular",
  CLINICA_MEDICA = "Clínica Médica",
  COLOPROCTOLOGIA = "Coloproctologia",
  DERMATOLOGIA = "Dermatologia",
  ENDOCRINOLOGIA_METABOLOGIA = "Endocrinologia e Metabologia",
  ENDOSCOPIA = "Endoscopia",
  GASTROENTEROLOGIA = "Gastroenterologia",
  GENETICA_MEDICA = "Genética Médica",
  GERIATRIA = "Geriatria",
  GINECOLOGIA_OBSTETRICIA = "Ginecologia e Obstetrícia",
  HEMATOLOGIA_HEMOTERAPIA = "Hematologia e Hemoterapia",
  HOMEOPATIA = "Homeopatia",
  INFECTOLOGIA = "Infectologia",
  MASTOLOGIA = "Mastologia",
  MEDICINA_DE_EMERGENCIA = "Medicina de Emergência",
  MEDICINA_DE_FAMILIA_COMUNIDADE = "Medicina de Família e Comunidade",
  MEDICINA_DO_TRABALHO = "Medicina do Trabalho",
  MEDICINA_DO_TRAFEGO = "Medicina do Tráfego",
  MEDICINA_ESPORTIVA = "Medicina Esportiva",
  MEDICINA_FISICA_REABILITACAO = "Medicina Física e Reabilitação",
  MEDICINA_INTENSIVA = "Medicina Intensiva",
  MEDICINA_LEGAL_PERICIA = "Medicina Legal e Perícia Médica",
  MEDICINA_NUCLEAR = "Medicina Nuclear",
  MEDICINA_PREVENTIVA_SOCIAL = "Medicina Preventiva e Social",
  NEFROLOGIA = "Nefrologia",
  NEUROCIRURGIA = "Neurocirurgia",
  NEUROLOGIA = "Neurologia",
  NUTROLOGIA = "Nutrologia",
  OFTALMOLOGIA = "Oftalmologia",
  ONCOLOGIA_CLINICA = "Oncologia Clínica",
  ORTOPEDIA_TRAUMATOLOGIA = "Ortopedia e Traumatologia",
  OTORRINOLARINGOLOGIA = "Otorrinolaringologia",
  PATOLOGIA = "Patologia",
  PATOLOGIA_CLINICA = "Patologia Clínica/Medicina Laboratorial",
  PEDIATRIA = "Pediatria",
  PNEUMOLOGIA = "Pneumologia",
  PSIQUIATRIA = "Psiquiatria",
  RADIOLOGIA_DIAGNOSTICO = "Radiologia e Diagnóstico por Imagem",
  RADIOTERAPIA = "Radioterapia",
  REUMATOLOGIA = "Reumatologia",
  UROLOGIA = "Urologia",
}

export const medicalSpecialties = Object.entries(MedicalSpecialty).map(
  ([key, value]) => ({
    value: MedicalSpecialty[key as keyof typeof MedicalSpecialty],
    label: value,
  }),
);

export const dayOfWeekOptions = [
  { value: "0", label: "Domingo" },
  { value: "1", label: "Segunda-feira" },
  { value: "2", label: "Terça-feira" },
  { value: "3", label: "Quarta-feira" },
  { value: "4", label: "Quinta-feira" },
  { value: "5", label: "Sexta-feira" },
  { value: "6", label: "Sábado" },
];

export const timeOfDayOptions = [
  {
    label: "Manhã",
    options: [
      { value: "06:00:00", label: "06:00" },
      { value: "06:30:00", label: "06:30" },
      { value: "07:00:00", label: "07:00" },
      { value: "07:30:00", label: "07:30" },
      { value: "08:00:00", label: "08:00" },
      { value: "08:30:00", label: "08:30" },
      { value: "09:00:00", label: "09:00" },
      { value: "09:30:00", label: "09:30" },
      { value: "10:00:00", label: "10:00" },
      { value: "10:30:00", label: "10:30" },
      { value: "11:00:00", label: "11:00" },
      { value: "11:30:00", label: "11:30" },
    ],
  },
  {
    label: "Tarde",
    options: [
      { value: "12:00:00", label: "12:00" },
      { value: "12:30:00", label: "12:30" },
      { value: "13:00:00", label: "13:00" },
      { value: "13:30:00", label: "13:30" },
      { value: "14:00:00", label: "14:00" },
      { value: "14:30:00", label: "14:30" },
      { value: "15:00:00", label: "15:00" },
      { value: "15:30:00", label: "15:30" },
      { value: "16:00:00", label: "16:00" },
      { value: "16:30:00", label: "16:30" },
      { value: "17:00:00", label: "17:00" },
      { value: "17:30:00", label: "17:30" },
    ],
  },
  {
    label: "Noite",
    options: [
      { value: "18:00:00", label: "18:00" },
      { value: "18:30:00", label: "18:30" },
      { value: "19:00:00", label: "19:00" },
      { value: "19:30:00", label: "19:30" },
      { value: "20:00:00", label: "20:00" },
      { value: "20:30:00", label: "20:30" },
      { value: "21:00:00", label: "21:00" },
      { value: "21:30:00", label: "21:30" },
      { value: "22:00:00", label: "22:00" },
      { value: "22:30:00", label: "22:30" },
      { value: "23:00:00", label: "23:00" },
      { value: "23:30:00", label: "23:30" },
    ],
  },
];
